import { COMPRESSOR_PARAMETER_OPTIONS } from './compressorLogs';
import { ENERGY_PARAMETER_OPTIONS } from './energyAnalytics';
import { FIRE_SAFETY_PARAMETER_OPTIONS } from './fireSafetyLogs';
import { FUEL_PARAMETER_OPTIONS } from './fuelLogs';
import { SOLAR_PARAMETER_OPTIONS } from './solarLogs';
import { TEMPERATURE_PARAMETER_OPTIONS } from './temperatureLogs';
import { WATER_PARAMETER_OPTIONS } from './waterLogs';

export const PARAMETER_OPTIONS = {
	ENERGY: ENERGY_PARAMETER_OPTIONS,
	SOLAR: SOLAR_PARAMETER_OPTIONS,
	TEMPERATURE: TEMPERATURE_PARAMETER_OPTIONS,
	'FIRE-SAFETY': FIRE_SAFETY_PARAMETER_OPTIONS,
	COMPRESSOR: COMPRESSOR_PARAMETER_OPTIONS,
	WATER: WATER_PARAMETER_OPTIONS,
	FUEL: FUEL_PARAMETER_OPTIONS,
};
